const CATEGORIES = {
  LOAD: 'CATEGORIES_LOAD',
  LOAD_SUCCESS: 'CATEGORIES_LOAD_SUCCESS',
  LOAD_FAIL: 'CATEGORIES_LOAD_FAIL',
};

const LOG_POINTS = {
  POST_REQUEST: 'LOG_POINTS_REQUEST',
  POST_SUCCESS: 'LOG_POINTS_POST_SUCCESS',
  POST_FAIL: 'LOG_POINTS_FAIL',
};


export { LOG_POINTS, CATEGORIES };
