const APPROVE_ACTIVITY_REQUEST = 'APPROVE_ACTIVITY_REQUEST';
const APPROVE_ACTIVITY_SUCCESS = 'APPROVE_ACTIVITY_SUCCESS';
const APPROVE_ACTIVITY_PAGE_ERROR = 'APPROVE_ACTIVITY_PAGE_ERROR';
const APPROVE_ACTIVITY_PAGE_LOADING = 'APPROVE_ACTIVITY_PAGE_LOADING';
const RESET_APPROVE_ACTIVITY_STATUS = 'RESET_APPROVE_ACTIVITY_STATUS';

const REJECT_ACTIVITY_REQUEST = 'REJECT_ACTIVITY_REQUEST';
const REJECT_ACTIVITY_SUCCESS = 'REJECT_ACTIVITY_SUCCESS';
const REJECT_ACTIVITY_PAGE_ERROR = 'REJECT_ACTIVITY_PAGE_ERROR';
const REJECT_ACTIVITY_PAGE_LOADING = 'REJECT_ACTIVITY_PAGE_LOADING';
const RESET_REJECT_ACTIVITY_STATUS = 'RESET_REJECT_ACTIVITY_STATUS';

export default {
  APPROVE_ACTIVITY_REQUEST,
  APPROVE_ACTIVITY_SUCCESS,
  APPROVE_ACTIVITY_PAGE_ERROR,
  APPROVE_ACTIVITY_PAGE_LOADING,
  RESET_APPROVE_ACTIVITY_STATUS,

  REJECT_ACTIVITY_REQUEST,
  REJECT_ACTIVITY_SUCCESS,
  REJECT_ACTIVITY_PAGE_ERROR,
  REJECT_ACTIVITY_PAGE_LOADING,
  RESET_REJECT_ACTIVITY_STATUS,
};
