const FETCH_USER_ROLE_REQUEST = 'FETCH_USER_ROLE_REQUEST';
const FETCH_USER_ROLE_SUCCESS = 'FETCH_USER_ROLE_SUCCESS';
const FETCH_USER_ROLE_ERROR = 'FETCH_USER_ROLE_ERROR';

export default {
  FETCH_USER_ROLE_ERROR,
  FETCH_USER_ROLE_REQUEST,
  FETCH_USER_ROLE_SUCCESS,
};
