export const FETCH_USER_INFO = 'FETCH_USER_INFO';

// my activities
export const MY_ACTIVITIES_GET_REQUEST = 'MY_ACTIVITIES_GET_REQUEST';
export const MY_ACTIVITIES_GET_SUCCESS = 'MY_ACTIVITIES_GET_SUCCESS';
export const MY_ACTIVITIES_GET_FAILURE = 'MY_ACTIVITIES_GET_FAILURE';
