const FETCH_USER_ACTIVITIES_REQUEST = 'FETCH_USER_ACTIVITIES_REQUEST';
const FETCH_USER_ACTIVITIES_SUCCESS = 'FETCH_USER_ACTIVITIES_SUCCESS';
const FETCH_USER_ACTIVITIES_ERROR = 'FETCH_USER_ACTIVITIES_ERROR';

const LOG_POINTS = {
  POST_REQUEST: 'LOG_POINTS_REQUEST',
  POST_SUCCESS: 'LOG_POINTS_POST_SUCCESS',
  POST_FAIL: 'LOG_POINTS_FAIL',
};

const CATEGORIES = {
  LOAD: 'CATEGORIES_LOAD',
  LOAD_SUCCESS: 'CATEGORIES_LOAD_SUCCESS',
  LOAD_FAIL: 'CATEGORIES_LOAD_FAIL',
};

export default {
  FETCH_USER_ACTIVITIES_ERROR,
  FETCH_USER_ACTIVITIES_REQUEST,
  FETCH_USER_ACTIVITIES_SUCCESS,
  LOG_POINTS,
  CATEGORIES,
};
