const FETCH_USER_ACTIVITIES_REQUEST = 'FETCH_USER_ACTIVITIES_REQUEST';
const FETCH_USER_ACTIVITIES_SUCCESS = 'FETCH_USER_ACTIVITIES_SUCCESS';
const FETCH_USER_ACTIVITIES_ERROR = 'FETCH_USER_ACTIVITIES_ERROR';
const LOG_POINTS_REQUEST = 'LOG_POINTS_REQUEST';
const LOG_POINTS_SUCCESS = 'LOG_POINTS_SUCCESS';
const LOG_POINTS_FAIL = 'LOG_POINTS_FAIL';
const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
const CATEGORIES_FAIL = 'CATEGORIES_FAIL';

export default {
  FETCH_USER_ACTIVITIES_ERROR,
  FETCH_USER_ACTIVITIES_REQUEST,
  FETCH_USER_ACTIVITIES_SUCCESS,
  LOG_POINTS_FAIL,
  LOG_POINTS_REQUEST,
  LOG_POINTS_SUCCESS,
  CATEGORIES_REQUEST,
  CATEGORIES_SUCCESS,
  CATEGORIES_FAIL,
};
