const FETCH_SOCIETY_INFO_REQUEST = 'FETCH_SOCIETY_INFO_REQUEST';
const FETCH_SOCIETY_INFO_SUCCESS = 'FETCH_SOCIETY_INFO_SUCCESS';
const SOCIETY_PAGE_LOADING = 'SOCIETY_PAGE_LOADING';
const SOCIETY_PAGE_ERROR = 'SOCIETY_PAGE_ERROR';

export default {
  SOCIETY_PAGE_ERROR,
  SOCIETY_PAGE_LOADING,
  FETCH_SOCIETY_INFO_REQUEST,
  FETCH_SOCIETY_INFO_SUCCESS,
}
