// page action types
export const TITLE_CHANGE = 'TITLE_CHANGE';

// user info action types
export const FETCH_USER_INFO = 'FETCH_USER_INFO';

// my activities action types
export const FETCH_MY_ACTIVITIES_REQUEST = 'FETCH_MY_ACTIVITIES_REQUEST';
export const FETCH_MY_ACTIVITIES_SUCCESS = 'FETCH_MY_ACTIVITIES_SUCCESS';
export const FETCH_MY_ACTIVITIES_FAILURE = 'FETCH_MY_ACTIVITIES_FAILURE';

// create activity action type
export const CREATE_ACTIVITY_REQUEST = 'CREATE_ACTIVITY_REQUEST';
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';
export const CREATE_ACTIVITY_FAILURE = 'CREATE_ACTIVITY_FAILURE';

// society info action types
export const FETCH_SOCIETY_INFO_REQUEST = 'FETCH_SOCIETY_INFO_REQUEST';
export const FETCH_SOCIETY_INFO_SUCCESS = 'FETCH_SOCIETY_INFO_SUCCESS';
export const FETCH_SOCIETY_INFO_FAILURE = 'FETCH_SOCIETY_INFO_FAILURE';

// categories types
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

// user profile action types
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';
