// page action types
export const TITLE_CHANGE = 'TITLE_CHANGE';

// user info action types
export const FETCH_USER_INFO = 'FETCH_USER_INFO';

// my activities action types
export const FETCH_MY_ACTIVITIES_REQUEST = 'FETCH_MY_ACTIVITIES_REQUEST';
export const FETCH_MY_ACTIVITIES_SUCCESS = 'FETCH_MY_ACTIVITIES_SUCCESS';
export const FETCH_MY_ACTIVITIES_FAILURE = 'FETCH_MY_ACTIVITIES_FAILURE';
export const UPDATE_MY_ACTIVITIES_SUCCESS = 'UPDATE_MY_ACTIVITIES_SUCCESS';
export const UPDATE_MY_ACTIVITIES_FAILURE = 'UPDATE_MY_ACTIVITIES_FAILURE';
export const UPDATE_MY_ACTIVITIES = 'UPDATE_MY_ACTIVITIES';

// create activity action type
export const CREATE_ACTIVITY_REQUEST = 'CREATE_ACTIVITY_REQUEST';
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';
export const CREATE_ACTIVITY_FAILURE = 'CREATE_ACTIVITY_FAILURE';

// society info action types
export const FETCH_SOCIETY_INFO_REQUEST = 'FETCH_SOCIETY_INFO_REQUEST';
export const FETCH_SOCIETY_INFO_SUCCESS = 'FETCH_SOCIETY_INFO_SUCCESS';
export const FETCH_SOCIETY_INFO_FAILURE = 'FETCH_SOCIETY_INFO_FAILURE';

// categories types
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

// user profile action types
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

// redeem points action types
export const CREATE_REDEEM_POINTS_REQUEST = 'CREATE_REDEEM_POINTS_REQUEST';
export const CREATE_REDEEM_POINTS_SUCCESS = 'CREATE_REDEEM_POINTS_SUCCESS';
export const CREATE_REDEEM_POINTS_FAILURE = 'CREATE_REDEEM_POINTS_FAILURE';

// redemption types
export const FETCH_REDEMPTIONS_REQUEST = 'FETCH_REDEMPTIONS_REQUEST';
export const FETCH_REDEMPTIONS_SUCCESS = 'FETCH_REDEMPTIONS_SUCCESS';
export const FETCH_REDEMPTIONS_FAILURE = 'FETCH_REDEMPTIONS_FAILURE';

// verify activity action types
export const VERIFY_ACTIVITY_REQUEST = 'VERIFY_ACTIVITY_REQUEST';
export const VERIFY_ACTIVITY_SUCCESS = 'VERIFY_ACTIVITY_SUCCESS';
export const VERIFY_ACTIVITY_FAILURE = 'VERIFY_ACTIVITY_FAILURE';

// verify redemption action types
export const VERIFY_REDEMPTION_REQUEST = 'VERIFY_REDEMPTION_REQUEST';
export const VERIFY_REDEMPTION_SUCCESS = 'VERIFY_REDEMPTION_SUCCESS';
export const VERIFY_REDEMPTION_FAILURE = 'VERIFY_REDEMPTION_FAILURE';

// complete redemptions finance action types
export const COMPLETE_REDEMPTION_FINANCE_REQUEST = 'COMPLETE_REDEMPTION_FINANCE_REQUEST';
export const COMPLETE_REDEMPTION_FINANCE_SUCCESS = 'COMPLETE_REDEMPTION_FINANCE_SUCCESS';
export const COMPLETE_REDEMPTION_FINANCE_FAILURE = 'COMPLETE_REDEMPTION_FINANCE_FAILURE';

// update redemption action types
export const UPDATE_REDEMPTION_REQUEST = 'UPDATE_REDEMPTION_REQUEST';
export const UPDATE_REDEMPTION_SUCCESS = 'UPDATE_REDEMPTION_SUCCESS';
export const UPDATE_REDEMPTION_FAILURE = 'UPDATE_REDEMPTION_FAILURE';

// all activities action types
export const FETCH_ALL_ACTIVITIES_REQUEST = 'FETCH_ALL_ACTIVITIES_REQUEST';
export const FETCH_ALL_ACTIVITIES_SUCCESS = 'FETCH_ALL_ACTIVITIES_SUCCESS';
export const FETCH_ALL_ACTIVITIES_FAILURE = 'FETCH_ALL_ACTIVITIES_FAILURE';

// comment action types
export const MORE_INFO_REQUEST = 'MORE_INFO_REQUEST';
export const MORE_INFO_SUCCESS = 'MORE_INFO_SUCCESS';
export const MORE_INFO_FAILURE = 'MORE_INFO_FAILURE';
// create category action types
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

// create category action types
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

// show modal action types
export const OPEN_MODAL_SUCCESS = 'OPEN_MODAL_SUCCESS';
export const CLOSE_MODAL_SUCCESS = 'CLOSE_MODAL_SUCCESS';

// edit category action types
export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';

// approve activity by success ops
export const APPROVE_ACTIVITY_BY_OPS_REQUEST = 'APPROVE_ACTIVITY_BY_OPS_REQUEST';
export const APPROVE_ACTIVITY_BY_OPS_SUCCESS = 'APPROVE_ACTIVITY_BY_OPS_SUCCESS';
export const APPROVE_ACTIVITY_BY_OPS_FAILURE = 'APPROVE_ACTIVITY_BY_OPS_FAILURE';

// reject activity by success ops
export const REJECT_ACTIVITY_BY_OPS_REQUEST = 'REJECT_ACTIVITY_BY_OPS_REQUEST';
export const REJECT_ACTIVITY_BY_OPS_SUCCESS = 'REJECT_ACTIVITY_BY_OPS_SUCCESS';
export const REJECT_ACTIVITY_BY_OPS_FAILURE = 'REJECT_ACTIVITY_BY_OPS_FAILURE';
